# AgentKit: generated from pinned agentsessions sources (Apache-2.0); imports made package-relative.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import harness_pb2 as harness__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in harness_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarnessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/agentsessions.v1.Harness/Describe',
                request_serializer=harness__pb2.DescribeRequest.SerializeToString,
                response_deserializer=harness__pb2.HarnessDescriptor.FromString,
                _registered_method=True)
        self.Connect = channel.stream_stream(
                '/agentsessions.v1.Harness/Connect',
                request_serializer=harness__pb2.ControllerFrame.SerializeToString,
                response_deserializer=common__pb2.Event.FromString,
                _registered_method=True)


class HarnessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Describe returns the static contract; used to match the harness to a runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request_iterator, context):
        """Connect drives ONE execution. The host sends Start (and optional control frames);
        the harness streams Events terminated by exactly one EVENT_END.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=harness__pb2.DescribeRequest.FromString,
                    response_serializer=harness__pb2.HarnessDescriptor.SerializeToString,
            ),
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=harness__pb2.ControllerFrame.FromString,
                    response_serializer=common__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentsessions.v1.Harness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentsessions.v1.Harness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Harness(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentsessions.v1.Harness/Describe',
            harness__pb2.DescribeRequest.SerializeToString,
            harness__pb2.HarnessDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agentsessions.v1.Harness/Connect',
            harness__pb2.ControllerFrame.SerializeToString,
            common__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
